
// This file has been generated by the GUI designer. Do not modify.
namespace jzeferino.XSAddin.Wizard
{
	public partial class GtkSolutionTemplateWizardWidget
	{
		private global::Gtk.VBox vbox19;

		private global::Gtk.VBox vbox22;

		private global::Gtk.VBox vbox23;

		private global::Gtk.Label label7;

		private global::Gtk.HSeparator hseparator21;

		private global::Gtk.Label label8;

		private global::Gtk.VBox vbox24;

		private global::Gtk.HBox hbox4;

		private global::Gtk.RadioButton radioNative;

		private global::Gtk.RadioButton radioForms;

		private global::Gtk.VBox vbox27;

		private global::Gtk.VBox vbox28;

		private global::Gtk.HSeparator hseparator22;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label11;

		private global::Gtk.Entry entryApplicationIdentifier;

		private global::Gtk.HSeparator hseparator28;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label13;

		private global::Gtk.Entry entryApplicationName;

		private global::Gtk.HSeparator hseparator29;

		private global::Gtk.Label label12;

		private global::Gtk.VBox vbox29;

		private global::Gtk.HBox hbox9;

		private global::Gtk.CheckButton checkboxAndroidProject;

		private global::Gtk.CheckButton checkboxiOSProject;

		private global::Gtk.HBox hbox10;

		private global::Gtk.CheckButton checkboxUnitTestsProject;

		private global::Gtk.HSeparator hseparator23;

		private global::Gtk.VBox vbox25;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox26;

		private global::Gtk.HBox hbox5;

		private global::Gtk.CheckButton checkboxSharedCode;

		private global::Gtk.VBox vbox21;

		private global::Gtk.HSeparator hseparator24;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox20;

		private global::Gtk.HBox hbox8;

		private global::Gtk.CheckButton checkboxGit;

		private global::Gtk.CheckButton checkboxReadme;

		private global::Gtk.CheckButton checkboxCake;

		private global::Gtk.CheckButton checkboxFolderStructure;

		private global::Gtk.HSeparator hseparator16;

		private global::Gtk.VPaned vpaned2;

		private global::Gtk.Label label14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget jzeferino.XSAddin.Wizard.GtkSolutionTemplateWizardWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "jzeferino.XSAddin.Wizard.GtkSolutionTemplateWizardWidget";
			// Container child jzeferino.XSAddin.Wizard.GtkSolutionTemplateWizardWidget.Gtk.Container+ContainerChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 10;
			this.vbox19.BorderWidth = ((uint)(30));
			// Container child vbox19.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.vbox23 = new global::Gtk.VBox();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Customize");
			this.vbox23.Add(this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hseparator21 = new global::Gtk.HSeparator();
			this.hseparator21.Name = "hseparator21";
			this.vbox23.Add(this.hseparator21);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.hseparator21]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Solution type:");
			this.vbox23.Add(this.label8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.label8]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			this.vbox22.Add(this.vbox23);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.vbox23]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.radioNative = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Xamarin.Native"));
			this.radioNative.CanFocus = true;
			this.radioNative.Name = "radioNative";
			this.radioNative.DrawIndicator = true;
			this.radioNative.UseUnderline = true;
			this.radioNative.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox4.Add(this.radioNative);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.radioNative]));
			w5.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.radioForms = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Xamarin.Forms"));
			this.radioForms.CanFocus = true;
			this.radioForms.Name = "radioForms";
			this.radioForms.DrawIndicator = true;
			this.radioForms.UseUnderline = true;
			this.radioForms.Group = this.radioNative.Group;
			this.hbox4.Add(this.radioForms);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.radioForms]));
			w6.Position = 1;
			this.vbox24.Add(this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hseparator22 = new global::Gtk.HSeparator();
			this.hseparator22.Name = "hseparator22";
			this.vbox28.Add(this.hseparator22);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hseparator22]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Application identifier:");
			this.hbox11.Add(this.label11);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label11]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entryApplicationIdentifier = new global::Gtk.Entry();
			this.entryApplicationIdentifier.TooltipMarkup = "The package name / bundle indentifier.";
			this.entryApplicationIdentifier.CanFocus = true;
			this.entryApplicationIdentifier.Name = "entryApplicationIdentifier";
			this.entryApplicationIdentifier.Text = global::Mono.Unix.Catalog.GetString("com.example.yourapplication");
			this.entryApplicationIdentifier.IsEditable = true;
			this.entryApplicationIdentifier.MaxLength = 30;
			this.entryApplicationIdentifier.InvisibleChar = '●';
			this.hbox11.Add(this.entryApplicationIdentifier);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entryApplicationIdentifier]));
			w10.Position = 1;
			this.vbox28.Add(this.hbox11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox11]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hseparator28 = new global::Gtk.HSeparator();
			this.hseparator28.Name = "hseparator28";
			this.vbox28.Add(this.hseparator28);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hseparator28]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Application name:      ");
			this.hbox12.Add(this.label13);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label13]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.entryApplicationName = new global::Gtk.Entry();
			this.entryApplicationName.TooltipMarkup = "The application name.";
			this.entryApplicationName.CanFocus = true;
			this.entryApplicationName.Name = "entryApplicationName";
			this.entryApplicationName.Text = global::Mono.Unix.Catalog.GetString("YourApplication");
			this.entryApplicationName.IsEditable = true;
			this.entryApplicationName.MaxLength = 30;
			this.entryApplicationName.InvisibleChar = '●';
			this.hbox12.Add(this.entryApplicationName);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entryApplicationName]));
			w14.Position = 1;
			this.vbox28.Add(this.hbox12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox12]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hseparator29 = new global::Gtk.HSeparator();
			this.hseparator29.Name = "hseparator29";
			this.vbox28.Add(this.hseparator29);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hseparator29]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Projects to include:");
			this.vbox28.Add(this.label12);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label12]));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(5));
			// Container child vbox28.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.checkboxAndroidProject = new global::Gtk.CheckButton();
			this.checkboxAndroidProject.CanFocus = true;
			this.checkboxAndroidProject.Name = "checkboxAndroidProject";
			this.checkboxAndroidProject.Label = global::Mono.Unix.Catalog.GetString("Xamarin.Android");
			this.checkboxAndroidProject.DrawIndicator = true;
			this.checkboxAndroidProject.UseUnderline = true;
			this.hbox9.Add(this.checkboxAndroidProject);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.checkboxAndroidProject]));
			w18.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.checkboxiOSProject = new global::Gtk.CheckButton();
			this.checkboxiOSProject.CanFocus = true;
			this.checkboxiOSProject.Name = "checkboxiOSProject";
			this.checkboxiOSProject.Label = global::Mono.Unix.Catalog.GetString("Xamarin.iOS");
			this.checkboxiOSProject.DrawIndicator = true;
			this.checkboxiOSProject.UseUnderline = true;
			this.hbox9.Add(this.checkboxiOSProject);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.checkboxiOSProject]));
			w19.Position = 1;
			this.vbox29.Add(this.hbox9);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox9]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.checkboxUnitTestsProject = new global::Gtk.CheckButton();
			this.checkboxUnitTestsProject.CanFocus = true;
			this.checkboxUnitTestsProject.Name = "checkboxUnitTestsProject";
			this.checkboxUnitTestsProject.Label = global::Mono.Unix.Catalog.GetString("Unit.Test");
			this.checkboxUnitTestsProject.DrawIndicator = true;
			this.checkboxUnitTestsProject.UseUnderline = true;
			this.hbox10.Add(this.checkboxUnitTestsProject);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.checkboxUnitTestsProject]));
			w21.Position = 0;
			this.vbox29.Add(this.hbox10);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox10]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox28.Add(this.vbox29);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.vbox29]));
			w23.Position = 6;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox27.Add(this.vbox28);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.vbox28]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox24.Add(this.vbox27);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.vbox27]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox22.Add(this.vbox24);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.vbox24]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.hseparator23 = new global::Gtk.HSeparator();
			this.hseparator23.Name = "hseparator23";
			this.vbox22.Add(this.hseparator23);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.hseparator23]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Portable Class Library Shared Code:");
			this.vbox25.Add(this.label9);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.label9]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(5));
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.checkboxSharedCode = new global::Gtk.CheckButton();
			this.checkboxSharedCode.Name = "checkboxSharedCode";
			this.checkboxSharedCode.Label = global::Mono.Unix.Catalog.GetString("Add shared code");
			this.checkboxSharedCode.Active = true;
			this.checkboxSharedCode.DrawIndicator = true;
			this.checkboxSharedCode.UseUnderline = true;
			this.hbox5.Add(this.checkboxSharedCode);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.checkboxSharedCode]));
			w29.Position = 0;
			this.vbox26.Add(this.hbox5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox5]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox25.Add(this.vbox26);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox26]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox22.Add(this.vbox25);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.vbox25]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox19.Add(this.vbox22);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.vbox22]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.hseparator24 = new global::Gtk.HSeparator();
			this.hseparator24.Name = "hseparator24";
			this.vbox21.Add(this.hseparator24);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.hseparator24]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox21.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Other:");
			this.vbox21.Add(this.label10);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.label10]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			w35.Padding = ((uint)(5));
			this.vbox19.Add(this.vbox21);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.vbox21]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.checkboxGit = new global::Gtk.CheckButton();
			this.checkboxGit.CanFocus = true;
			this.checkboxGit.Name = "checkboxGit";
			this.checkboxGit.Label = global::Mono.Unix.Catalog.GetString(".gitignore (override default)");
			this.checkboxGit.DrawIndicator = true;
			this.checkboxGit.UseUnderline = true;
			this.hbox8.Add(this.checkboxGit);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkboxGit]));
			w37.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.checkboxReadme = new global::Gtk.CheckButton();
			this.checkboxReadme.CanFocus = true;
			this.checkboxReadme.Name = "checkboxReadme";
			this.checkboxReadme.Label = global::Mono.Unix.Catalog.GetString("README.md");
			this.checkboxReadme.DrawIndicator = true;
			this.checkboxReadme.UseUnderline = true;
			this.hbox8.Add(this.checkboxReadme);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkboxReadme]));
			w38.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.checkboxCake = new global::Gtk.CheckButton();
			this.checkboxCake.CanFocus = true;
			this.checkboxCake.Name = "checkboxCake";
			this.checkboxCake.Label = global::Mono.Unix.Catalog.GetString("Cake");
			this.checkboxCake.DrawIndicator = true;
			this.checkboxCake.UseUnderline = true;
			this.hbox8.Add(this.checkboxCake);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkboxCake]));
			w39.Position = 2;
			// Container child hbox8.Gtk.Box+BoxChild
			this.checkboxFolderStructure = new global::Gtk.CheckButton();
			this.checkboxFolderStructure.TooltipMarkup = "Map project folder structure in solution with solution folders.";
			this.checkboxFolderStructure.CanFocus = true;
			this.checkboxFolderStructure.Name = "checkboxFolderStructure";
			this.checkboxFolderStructure.Label = global::Mono.Unix.Catalog.GetString("Map solution folders");
			this.checkboxFolderStructure.DrawIndicator = true;
			this.checkboxFolderStructure.UseUnderline = true;
			this.hbox8.Add(this.checkboxFolderStructure);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkboxFolderStructure]));
			w40.Position = 3;
			this.vbox20.Add(this.hbox8);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox8]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hseparator16 = new global::Gtk.HSeparator();
			this.hseparator16.Name = "hseparator16";
			this.vbox20.Add(this.hseparator16);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hseparator16]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox19.Add(this.vbox20);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.vbox20]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.vpaned2 = new global::Gtk.VPaned();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			this.vbox19.Add(this.vpaned2);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.vpaned2]));
			w44.Position = 3;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Yalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("jzeferino");
			this.label14.Justify = ((global::Gtk.Justification)(3));
			this.vbox19.Add(this.label14);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label14]));
			w45.Position = 4;
			w45.Expand = false;
			w45.Fill = false;
			this.Add(this.vbox19);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
